# Site settings
title: Oktavianto
header-img: img/home-bg.jpg
email: excel@oktavianto.id
copyright_name: Oktavianto
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "https://oktavianto.github.io"
twitter_username: ExcelDwiO
github_username:  oktavianto
facebook_username:  nothyz
email_username:  excel@oktavianto.id

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
